services:
  app1:
    image: paolini/olifogli
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/olifogli
      - NEXTAUTH_URL=https://<your server>/api/auth
      - NEXT_PUBLIC_APP_INSTANCE=app1
    networks:
      - backend

  app2:
    image: paolini/olifogli
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/olifogli
      - NEXTAUTH_URL=https://<your server>/api/auth
      - NEXT_PUBLIC_APP_INSTANCE=app2
    networks:
      - backend

  app3:
    image: paolini/olifogli
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/olifogli
      - NEXTAUTH_URL=https://<your server>/api/auth
      - NEXT_PUBLIC_APP_INSTANCE=app3
    networks:
      - backend

  db:
    image: mongo
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    networks:
      - backend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - backend

networks:
  backend:
