#
# Per aggiornare
#   sudo docker compose pull
#
# Per riavviare
#   sudo docker compose up -d
#
# Se si vuole mandare in stop tutti i container contiene prima fermare i due "worker" che ci mettono piu' tempo:
#   sudo docker compose down oliscan olisheet
#
# Poi si possono fermare tutti gli altri, a quel punto sarà quasi istantaneo:
#   sudo docker compose down
#
# Per eseguire uno script:
#   sudo docker compose exec [-T] app1 node scripts/test.js
#
# Per vedere le migrazioni del database:
#   sudo docker compose exec app1 npx migrate-mongo status
#
# Per fare un backup del database:
#   sudo docker compose exec -T db mongodump -d olifogli --archive > $(date -u +%Y-%m-%d-%H-%M)-database-backup.archive
#
# restore database: (WARNING! database will be overwritten!)
#   cat database-backup.archive | sudo docker compose exec -T db mongorestore --drop olifogli --archive

x-common-env: &common-env
    MONGODB_URI: "mongodb://db:27017/olifogli?replicaSet=rs0&retryWrites=true&w=majority"
    SCANS_SPOOL_DIR: "/app/spool"
    SCANS_DATA_DIR: "/app/data"
    SHEETGENDATA_DIR: "/app/sheetgendata"
    NEXTAUTH_SECRET: "..."
    NEXTAUTH_URL: "https://olifogli.matb.it"
    OLIMANAGER_URL: "https://olimpiadi-scientifiche.it"
    OLIMANAGER_OAUTH_CLIENT_ID: "..."
    OLIMANAGER_OAUTH_CLIENT_SECRET: "..."
    OLI_GRAPHQL_ENDPOINT: "https://olimpiadi-scientifiche.it/graphql/"
    ADMIN_EMAILS: "emanuele.paolini@unipi.it"
    LOG_DIR: "/app/logs"

x-app-common: &app-common
  image: paolini/olifogli:latest
  restart: unless-stopped
  volumes:
    - ./logs:/app/logs
    - ./spool:/app/spool
    - ./data:/app/data
    - ./sheetgenspool:/app/sheetgenspool
    - ./sheetgendata:/app/sheetgendata
  networks:
    - backend
#    ports:
#      - 8000:3000

services:
  app1:
    <<: *app-common
    environment:
      <<: *common-env
      NEXT_PUBLIC_APP_INSTANCE: "app1"

  app2:
    <<: *app-common
    environment:
      <<: *common-env
      NEXT_PUBLIC_APP_INSTANCE: "app2"

  app3:
    <<: *app-common
    environment:
      <<: *common-env
      NEXT_PUBLIC_APP_INSTANCE: "app3"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media:/media:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - backend

  oliscan:
    image: harbor.cs.dm.unipi.it/olifogli/oliscan
    restart: unless-stopped
    environment:
      - SPOOL_DIR=/app/spool
      - DATA_DIR=/app/data
      - MONGO_URI=mongodb://db:27017/olifogli?replicaSet=rs0&retryWrites=true&w=majority
    volumes:
      - ./spool:/app/spool
      - ./data:/app/data
    networks:
      - backend

  olisheet:
    image: harbor.cs.dm.unipi.it/olifogli/olisheet
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://db:27017/olifogli?replicaSet=rs0&retryWrites=true&w=majority
    volumes:
      - ./sheetgendata:/app/sheetgendata
      - ./sheetgenspool:/app/sheetgenspool
    networks:
      - backend

  db:
    image: mongo:6
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks:
      - backend

networks:
  backend:
