services:
  db:
    image: mongo
    environment:
    - PUID=1000
    - PGID=1000
    - NEXT_PUBLIC_APP_INSTANCE=app0
    volumes:
      - ./database:/data/db
    ports:
      - 127.0.0.1:27017:27017
    restart: unless-stopped
