name: Docker Image CI

on:
 push:
   branches:
     - main
     - develop

jobs:
  build:
    runs-on: ubuntu-latest
#    services:
#      mongodb:
#        image: mongo:latest
#        ports:
#          - 27017:27017
#        options: >-
#          --health-cmd "mongo --eval 'db.runCommand({ connectionStatus: 1 })'" 
#          --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
#    - name: Debug MongoDB logs
#      if: failure()
#      run: docker logs $(docker ps -aqf "ancestor=mongo:latest")
    - uses: actions/checkout@v3
    - name: Check running services
      run: docker ps -a
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install node packages
      run: npm ci
    - name: Build Js bundle (disabled)
      run: echo "disabled:" npm run build
    - name: Extract version number
      run: echo VERSION=$( node -e 'console.log(require("./package.json").version)' ) >> $GITHUB_ENV
    - name: Test version number and branch name
      run: echo version ${{ env.VERSION }} ref_name ${{ github.ref_name }} 
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: paolini/olifogli
        tags: |
          type=ref,event=tag
          type=ref,event=branch
          type=semver,pattern={{version}}
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      if: ${{ github.event_name != 'pull_request' }}
      with:
        push: true
        context: .
        tags: paolini/olifogli:latest , paolini/olifogli:${{ github.ref_name }} , paolini/olifogli:${{ env.VERSION }} 
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
